hosts: qalinux
  user: ansible
  connection: ssh
  become: yes

  vars:
    pkgname: httpd
    index_path: /var/www/html/

  tasks:
    - name: install apache
      action: yum pkg="{{pkgname}}" state=present
    - name: start apache
      action: service name="{{pkgname}}" state=started
    - name: deploy index file
      action: copy src=index.html dest="{{index_path}}"
